version: '3.8'

services:
  backend:
    image: ahamednazeer/waste-collection-scheduling:BE-0.1-
    container_name: waste-collection-backend
    ports:
      - "8000:8000" 
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./waste_collection.db
    restart: always

  frontend:
    image: ahamednazeer/waste-collection-scheduling:FE-0.1-amd
    container_name: waste-collection-frontend
    ports:
      - "3000:3000"
    environment:
      # If using server-side rendering to fetch data from backend
      - API_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
